using System;

namespace Electrons.Core.Net8
{
    /// <summary>
    /// Marks a property in a class as one to be included in a table generated by the html table helper.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class TableColumnAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the TableColumnAttribute class with no arguments.
        /// </summary>
        public TableColumnAttribute() { }

        /// <summary>
        /// Initializes a new instance of the TableColumnAttribute class with the specified display name.
        /// </summary>
        /// <param name="displayName">The header text for the column.</param>
        public TableColumnAttribute(string displayName)
        {
            HeaderText = displayName;
        }

        /// <summary>
        /// Initializes a new instance of the TableColumnAttribute class with the specified display name and sort order.
        /// </summary>
        /// <param name="displayName">The text to display in the header of the table.</param>
        /// <param name="sortorder">Value used to order the columns in the table in ascending order from left to right.</param>
        public TableColumnAttribute(string displayName, int sortorder)
            : this(displayName)
        {
            SortOrder = sortorder;
        }

        /// <summary>
        /// Optional parameter indicating the position of the column in order from left to right.  Default sort order is the order in which the parameters are listed in the class definition.
        /// </summary>
        public int SortOrder;

        /// <summary>
        /// Optional parameter to add an additional css class to the cells in the column
        /// </summary>
        public string Class;

        /// <summary>
        /// Optional parameter indication the text to display in the header of the table.  Default value is the property name.
        /// </summary>
        public string HeaderText;

        /// <summary>
        /// Optional parameter indicating if the column is displayed even if there is no data present.  Default value is false (column is always displayed).
        /// </summary>
        public bool Optional;

        /// <summary>
        /// Optional parameter indicating the property from which to get the header value if it needs to be dynamic.
        /// </summary>
        public string HeaderProperty;

        /// <summary>
        /// Gets or sets a value indicating if the field should be editable
        /// </summary>
        public bool Editable;

        public string Format;

        public string FooterProperty;
        public string ImageFormat;
        public string ColumnCss;
    }

    /// <summary>
    /// Marks a property in a class as one that should be displayed with a Hyperlink in each cell.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class LinkColumnAttribute : TableColumnAttribute
    {
        /// <summary>
        /// Initializes a new instance of the LinkColumnAttribute class with no arguments.
        /// </summary>
        public LinkColumnAttribute() { }

        /// <summary>
        /// Initializes a new instance of the LinkColumnAttribute class with the specified display name and sort order.
        /// </summary>
        /// <param name="navurl">The webpage that the generated hyperlink should navigate to when clicked.</param>
        public LinkColumnAttribute(string navurl)
        {
            NavUrl = navurl;
        }

        public LinkColumnAttribute(string navurl, bool fromRoot) : this(navurl)
        {
            FromRoot = fromRoot;
        }
        /// <summary>
        /// Required parameter indicating the webpage that the generated hyperlink should navigate to when clicked.
        /// </summary>
        public string NavUrl;
        public bool FromRoot;
    }

    /// <summary>
    /// Adds an additional route value to a generated link column, used in conjunction with the LinkColumnAttribute class.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
    public sealed class LinkParameterAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the LinkParameterAttribute class with no arguments.
        /// </summary>
        public LinkParameterAttribute() { }

        /// <summary>
        /// Initializes a new instance of the LinkParameterAttribute class with the specified parameter and field arguments.
        /// </summary>
        /// <param name="param">The name of the parameter to enter into the link's querystring.</param>
        /// <param name="field">The field or property in the class which stores the value you wish to pass in.</param>
        public LinkParameterAttribute(string param, string field)
        {
            Parameter = param;
            Field = field;
        }

        /// <summary>
        /// Required parameter indicating the name of the parameter to enter into the link's querystring.
        /// </summary>
        public string Parameter;

        /// <summary>
        /// Required parameter indicating the property in the class which stores the value you wish to pass in.
        /// </summary>
        public string Field;
    }

    //[AttributeUsage(AttributeTargets.Property)]
    //public sealed class ColumnTemplateAttribute:Attribute
    //{
    //    public ColumnTemplateAttribute(string template)
    //    {
    //        Template = template;
    //    }

    //    public string Template;
    //}

    [AttributeUsage(AttributeTargets.Property)]
    public sealed class DataAttributeAttribute : Attribute
    {
        public DataAttributeAttribute() { }

        public DataAttributeAttribute(string param)
        {
            Parameter = param;
        }

        public string Parameter;
    }
}
