services:
  electrons:
    image: sschus90/electronsnet8
    container_name: electronsnet8
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/keys:/app/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - GameSettings__DefaultConnection__Password=${DB_PASSWORD}